blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^admin2/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

blog/main/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from . import views, preblog, feeds, sitemaps


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.Post.as_view(), name='post'),
    url(r'^page/(?P<pk>[0-9]+)/$', views.Page.as_view(), name='page'),
    url(r'^archive$', views.Archive.as_view(), name='archive'),
    url(r'^authors/(?P<pk>[0-9]+)/$', views.Author.as_view(), name='author'),
]

urlpatterns += [
    url(r'^admin/$', views.AdminIndex.as_view(), name='admin_index'),
    url(r'^admin/meta$', views.AdminBlogMeta.as_view(), name='admin_blog_meta'),
    url(r'^admin/posts$', views.AdminPosts.as_view(), name='admin_posts'),
    url(r'^admin/pages$', views.AdminPosts.as_view(), {'is_blog_page':True}, name='admin_pages'),
    url(r'^admin/post$', views.AdminPost.as_view(), name='admin_post'),
    url(r'^admin/page$', views.AdminPage.as_view(), name='admin_page'),
    url(r'^admin/posts/(?P<pk>[0-9]+)$', views.AdminPost.as_view(), name='admin_edit_post'),
    url(r'^admin/pages/(?P<pk>[0-9]+)$', views.AdminPage.as_view(), name='admin_edit_page'),
    url(r'^admin/posts/delete/(?P<pk>[0-9]+)$', views.DeletePost.as_view(), name='admin_delete_post'),
    url(r'^admin/pages/delete/(?P<pk>[0-9]+)$', views.DeletePage.as_view(), name='admin_delete_page'),
    url(r'^admin/tags/$', views.AdminTags.as_view(), name='admin_tags'),
    url(r'^admin/category/$', views.AdminCategory.as_view(), name='admin_category'),
    url(r'^admin/filter-posts$', views.AdminFilterPosts.as_view(), name='admin_filter_posts'),
    url(r'^admin/tags/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'tag'}, name='admin_delete_tag'),
    url(r'^admin/categories/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'category'}, name='admin_delete_category'),
    url(r'^admin/tags/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'tag'}, name='admin_edit_tag'),
    url(r'^admin/categories/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'category'}, name='admin_edit_category'),
]

urlpatterns += [
    url(r'^init$', preblog.BlogInitView.as_view()),
    url(r'^reinit-meta$', preblog.ReInitBlogMetaView.as_view()),
    url(r'^rss/$', feeds.LatestEntriesFeed2(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps.sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/main/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
import markdown2

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=256, default='new blog')
    abstract = models.TextField(null=True, blank=True)
    raw = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    content_html = models.TextField(null=True, blank=True)
    author = models.ForeignKey(User)
    tags = models.ManyToManyField('Tag', blank=True)
    category = models.ForeignKey('Category', null=True, blank=True)
    is_draft = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post', kwargs={ 'pk': self.id })

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Page(models.Model):
    title = models.CharField(max_length=256, default='new page')
    slug = models.CharField(max_length=256, default='slug')
    raw = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    content_html = models.TextField()
    author = models.ForeignKey(User)
    is_draft = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:page', kwargs={ 'pk': self.id })

@python_2_unicode_compatible
class BlogMeta(models.Model):
    key = models.CharField(max_length=256)
    value = models.CharField(max_length=256, null=True, blank=True)
    flag = models.BooleanField(default=False)
    misc = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.key

blog/main/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

class NewPost(forms.Form):
    title = forms.CharField(max_length=256)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))
    abstract = forms.CharField(widget=forms.Textarea(attrs={'rows':4}), required=False)
    author_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    # tag = forms.CharField(max_length=256, required=False)
    # category = forms.CharField(max_length=256, required=False)

class NewPage(forms.Form):
    title = forms.CharField(max_length=256)
    slug = forms.CharField(max_length=64)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))
    author_id = forms.IntegerField(required=False, widget=forms.HiddenInput)

class CategoryForm(forms.Form):
    name = forms.CharField(max_length=256, label='Category Name')

class TagForm(forms.Form):
    tags = forms.CharField(max_length=256, label='Tags')

class BlogMetaForm(forms.Form):
    title = forms.CharField(max_length=256, label='Title')
    subtitle = forms.CharField(max_length=256, label='SubTitle')
    desc = forms.CharField(max_length=256, label='Description')
    author = forms.CharField(max_length=256, label='Owner')
    keywords = forms.CharField(max_length=256, label='Keywords')
    google_verify = forms.CharField(max_length=256, label='Google Site Verification', required=False)
    baidu_verify = forms.CharField(max_length=256, label='Baidu Site Verification', required=False)

blog/main/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse, Http404, HttpResponseForbidden
from django.views.generic import View
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# from django.utils.encoding import smart_text
from django.db.models import Count, Q
from django.contrib.auth.models import User

from guardian.shortcuts import assign_perm, get_perms
from guardian.core import ObjectPermissionChecker
from guardian.decorators import permission_required

# import markdown2

from . import models, forms, misc

# Create your views here.

PER_PAGE = settings.MAY_BLOG['PER_PAGE']
PER_PAGE_ADMIN = settings.MAY_BLOG['PER_PAGE_ADMIN']


def get_site_meta():
    seo = {}
    try:
        record = models.BlogMeta.objects.get(key='blog_name')
        seo['title'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    try:
        record = models.BlogMeta.objects.get(key='blog_desc')
        seo['desc'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    try:
        record = models.BlogMeta.objects.get(key='owner')
        seo['author'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    try:
        record = models.BlogMeta.objects.get(key='keywords')
        seo['keywords'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    try:
        record = models.BlogMeta.objects.get(key='blog_subtitle')
        seo['subtitle'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    try:
        record = models.BlogMeta.objects.get(key='google_verify')
        seo['google_verify'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    try:
        record = models.BlogMeta.objects.get(key='baidu_verify')
        seo['baidu_verify'] = record.value
    except models.BlogMeta.DoesNotExist:
        pass

    return seo

def get_user_info(user):
    try:
        data = {
            'username': user.username,
            'display_name': user.account.display_name,
            'biography': user.account.biography,
            'homepage': user.account.homepage,
            'weixin': user.account.weixin,
            'douban': user.account.douban,
            'twitter': user.account.twitter,
            'github': user.account.github,
            'weibo': user.account.weibo,
        }
    except:
        data = None

    return data

class Index(View):
    template_name = 'main/index.html'
    def get(self, request):
        data = {}
        
        tag = request.GET.get('tag')
        category = request.GET.get('category')
        keywords = request.GET.get('keywords')
        try:
            tag = int(tag) if tag else 0
            category = int(category) if category else 0
        except:
            raise Http404

        if tag:
            posts = filter_posts_by_tag(tag)
        elif category:
            posts = filter_posts_by_category(category)
        else:
            posts = models.Post.objects.all()
        posts = posts.filter(is_draft=False).order_by('-id')
        if keywords:
            posts = posts.filter(Q(title__contains=keywords) | Q(raw__contains=keywords))
            data['keywords'] = keywords
        post_pages = models.Page.objects.filter(is_draft=False)

        paginator = Paginator(posts, PER_PAGE)

        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)


        tags = models.Tag.objects.all()
        catagories = models.Category.objects.annotate(num_posts=Count('post'))

        data['posts'] = posts
        data['pages'] = post_pages
        data['tags'] = tags
        data['catagories'] = catagories
        data['category_id'] = category
        data['tag_id'] = tag

        data['seo'] = get_site_meta()

        return render(request, self.template_name, data)

class Post(View):
    template_name = 'main/post.html'
    def get(self, request, pk):
        try:
            pk = int(pk)
            post = models.Post.objects.get(pk=pk)
        except models.Post.DoesNotExist:
            raise Http404
        data = {'post':post}
        tags = post.tags.all()
        data['tags'] = tags

        comment_type = settings.MAY_BLOG['COMMENT_TYPE']
        comment_type_id = settings.MAY_BLOG['COMMENT_OPT'].get(comment_type)

        if not comment_type_id:
            comment_script = 'no comment script for {0}'.format(comment_type)
        else:
            comment_func = misc.get_comment_func(comment_type)
            # url_partial = [request.META['SERVER_NAME'], ':', request.META['SERVER_PORT'], request.path]
            # post_url = ''.join(url_partial)
            post_url = request.build_absolute_uri()
            comment_script = comment_func(request, comment_type_id, post.id, post.title, post_url)

        data['comment_script'] = comment_script

        data['jiathis_share'] = misc.jiathis_share(request)

        data['allow_donate'] = settings.MAY_BLOG['ALLOW_DONATE']

        seo = {
            'title': post.title, 
            'desc': post.abstract,
            'author': post.author.username,
            'keywords': ', '.join([tag.name for tag in tags])
        }

        data['seo'] = seo

        post_pages = models.Page.objects.filter(is_draft=False)
        data['pages'] = post_pages

        return render(request, self.template_name, data)

class Page(View):
    template_name = 'main/page.html'
    def get(self, request, pk):
        try:
            pk = int(pk)
            page = models.Page.objects.get(pk=pk)
        except models.Page.DoesNotExist:
            raise Http404
        data = {'page':page}
        data['seo'] = get_site_meta()

        post_pages = models.Page.objects.filter(is_draft=False)
        data['pages'] = post_pages

        return render(request, self.template_name, data)

class Archive(View):
    template_name = 'main/archive.html'
    def get(self, request):
        data = {}
        data['seo'] = get_site_meta()

        posts = models.Post.objects.filter(is_draft=False)
        paginator = Paginator(posts, PER_PAGE)

        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        data['posts'] = posts

        post_pages = models.Page.objects.filter(is_draft=False)
        data['pages'] = post_pages

        return render(request, self.template_name, data)

class Author(View):
    template_name = 'main/author.html'
    def get(self, request, pk):
        data = {}
        data['seo'] = get_site_meta()
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        data['user'] = user
        data['account_info'] = user.account

        posts = models.Post.objects.filter(is_draft=False, author=user)
        paginator = Paginator(posts, PER_PAGE)

        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)

        data['posts'] = posts

        return render(request, self.template_name, data)


class AdminIndex(View):
    template_name = 'blog_admin/index.html'
    @method_decorator(login_required)
    def get(self, request):
        data = {'site_info':get_site_meta(), 'account_info':get_user_info(request.user)}
        return render(request, self.template_name, data)

class AdminBlogMeta(View):
    template_name = 'main/simple_form.html'
    @method_decorator(permission_required('main.add_blogmeta', accept_global_perms=True))
    def get(self, request, form=None):
        if not form:
            form = forms.BlogMetaForm(initial=get_site_meta())

        data = {'form':form}
        return render(request, self.template_name, data)

    @method_decorator(permission_required('main.add_blogmeta', accept_global_perms=True))
    def post(self, request):
        form = forms.BlogMetaForm(request.POST)
        if form.is_valid():
            record = models.BlogMeta.objects.get(key='blog_name')
            record.value = form.cleaned_data['title']
            record.save()

            record = models.BlogMeta.objects.get(key='blog_desc')
            record.value = form.cleaned_data['desc']
            record.save()
            
            record = models.BlogMeta.objects.get(key='owner')
            record.value = form.cleaned_data['author']
            record.save()
            
            record = models.BlogMeta.objects.get(key='keywords')
            record.value = form.cleaned_data['keywords']
            record.save()
            
            record = models.BlogMeta.objects.get(key='blog_subtitle')
            record.value = form.cleaned_data['subtitle']
            record.save()

            record = models.BlogMeta.objects.get(key='google_verify')
            record.value = form.cleaned_data['google_verify']
            record.save()
            

blog/templates/main/author.html
{% extends 'base.html' %}
{% block title %} Author | {{ user.account.display_name }} {% endblock %}

{% load static %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-about-bg.jpg')">
        <div class="container">
            <div class="row">
                
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ seo.title }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ seo.subtitle }} <a href="{% url 'main:rss' %}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="row">
                        <h3>About Author </h3>
                        <hr>
                        <dl class="dl-horizontal">
                            <dt>Display Name:</dt>
                            <dd>{{account_info.display_name}}</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Biography:</dt>
                            <dd>{{account_info.biography}}</dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Social Network:</dt>
                            <dd>
                                {% if account_info.github %}
                                    <a href='{{ account_info.github }}'><i class="fa fa-github fa-lg"></i></a>
                                {% endif %}

                                {% if account_info.twitter %}
                                    <a href='{{ account_info.twitter }}'><i class="fa fa-twitter fa-lg"></i></a>
                                {% endif %}

                                {% if account_info.weibo %}
                                    <a href='{{ account_info.weibo }}'><i class="fa fa-weibo fa-lg"></i></a>
                                {% endif %}

                            </dd>
                        </dl>
                        <dl class="dl-horizontal">
                            <dt>Homepage:</dt>
                            <dd>
                                {% if account_info.homepage %}
                                <a href="{{ account_info.homepage }}"><i class="fa fa-home fa-lg"></i></a> {{ account_info.homepage }}
                                {% endif %}
                            </dd>
                        </dl>
                    </div>
                    
                </div>
            </div>
            
            <div class="row">

                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <h3>Articles</h3><hr>
                    <ul>
                        {% for post in posts %}
                        <li>
                        <a href="{% url 'main:post' post.id %}">{{ post.title }}</a>  
                           <!-- | <small><a href="{% url 'main:index' %}?category={{ post.category.id }}">{{ post.category.name }}</a></small> -->
                        </li>
                        {% empty %}
                        <p class="post-subtitle">
                            No articles found here
                        </p>
                        {% endfor %}
                    </ul>
                    <!-- Pager -->
                    <ul class="pager">
                        {% if posts.has_next %}
                        <li class="next">
                            <a href="?page={{ posts.next_page_number }}">Older Posts &rarr;</a>
                        </li>
                        {% endif %}
                        {% if posts.has_previous %}
                            <li class="next"><a href="?page={{ posts.previous_page_number }}">Previous Posts</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </article>

    <hr>

{% endblock %}

blog/templates/main/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ seo.title }}{% endblock %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>{{ seo.title }}</h1>
                        <hr class="small">
                        <span class="subheading">{{ seo.subtitle }} <a href="{% url 'main:rss' %}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-2 col-md-8 col-md-offset-1">
            {% for post in posts %}
            <div class="post-preview">
                <a href="{% url 'main:post' post.id %}">
                    <h2 class="post-title">
                        {{post.title}}
                    </h2>
                </a>
                <p class="post-subtitle">
                    {{post.abstract}}
                </p>
                <p class="post-meta">Posted by <a href="{% url 'main:author' post.author.id %}">{{ post.author.account.display_name }}</a> on {{ post.pub_time|date }}</p>
                <p class="post-meta">category: <a href="{% url 'main:index' %}?category={{ post.category.id }}">{{ post.category.name }}</a></p>
            </div>
            {% if not forloop.last %}
            <hr>
            {% endif %}
            {% empty %}
                <p class="post-subtitle">
                    No articles found here
                </p>
            {% endfor %}
            <!-- Pager -->
            <ul class="pager">
                {% if posts.has_next %}
                <li class="next">
                    <a href="?page={{ posts.next_page_number }}">Older Posts &rarr;</a>
                </li>
                {% endif %}
                {% if posts.has_previous %}
                    <li class="next"><a href="?page={{ posts.previous_page_number }}">Previous Posts</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="col-lg-3 col-md-2">
            <h3>Search</h3><hr/>
            <form id="search-form">
              <div class="form-group">
                <label class="sr-only" for="exampleInputAmount">Amount (in dollars)</label>
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-search"></i></div>
                  <input type="text" class="form-control" id="search" name="keywords" placeholder="search" value="{{ keywords }}">
                  <!-- <div class="input-group-addon">.00</div> -->
                </div>
              </div>
              <!-- <button type="submit" class="btn btn-default">Transfer cash</button> -->
            </form>
            <!-- <hr> -->
            <br>

            <h3>Tags</h3><hr/>
            {% for tag in tags %}
                <a href="?tag={{tag.id}}" class="post-tag">
                    {% if tag.id == tag_id %}
                    <span class="label label-primary">
                        {{ tag.name }}
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                    </span>
                    
                    {% else %}
                    <span class="label label-default">
                        {{ tag.name }}
                    </span>
                    
                    {% endif %}
                    
                </a>
                &nbsp;
            {% endfor %}
            
            <h3>Category</h3><hr/>
            <div class="list-group">
                {% for category in catagories %}
                    {% if category_id == category.id %}
                        <a href="?category={{category.id}}" class="list-group-item category-list active">{{ category.name }} 
                        <small><span class="glyphicon glyphicon-remove small rm-filter" aria-hidden="true"></span></small>
                        <span class="badge">&nbsp;{{category.num_posts}}&nbsp;</span></a>
                    {% else %}
                        <a href="?category={{category.id}}" class="list-group-item category-list ">{{ category.name }} 
                        <span class="badge">&nbsp;{{category.num_posts}}&nbsp;</span></a>
                    {% endif %}
                    
                {% endfor %}
            </div>

            <!-- <ul class="list-group">
                {% for category in catagories %}
                    {% if category_id == category.id %}
                        <li class="list-group-item category-list active">
                            <span class="badge">&nbsp;{{category.num_posts}}&nbsp;</span></a>
                            <a href="?category={{category.id}}">{{ category.name }} </a>
                            <a href="."><span class="glyphicon glyphicon-remove small" aria-hidden="true"></span></a>
                        </li>
                    {% else %}
                        <li class="list-group-item category-list">
                            <span class="badge">&nbsp;{{category.num_posts}}&nbsp;</span></a>
                            <a href="?category={{category.id}}">{{ category.name }} </a>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
 -->
            
        </div>
    </div>
</div>

<hr>
{% endblock %}

{% block js %}
<script type="text/javascript">
// $('#search').keyup(function(event){
//     if(event.keyCode == 13){
//         $("#search-form").submit();
//     }
// });

$('.rm-filter').on('click', function (event) {
    location.href = "{% url 'main:index' %}";
    return false;
  });
</script>
{% endblock %}

blog/templates/main/post.html
{% extends 'base.html' %}
{% block title %} {{post.title}} {% endblock %}

{% load static %}
{% block header %}
<header class="intro-header" style="background-image: url('http://7d9q7a.com1.z0.glb.clouddn.com/mayblog-home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>{{post.title}}</h1>
                        <!-- <h2 class="subheading">Problems look mighty small from 150 miles up</h2> -->
                        <span class="meta">Posted by <a href="{% url 'main:author' post.author.id %}">{{post.author.account.display_name}}</a> on {{post.pub_time}}</span>

                        <span class="meta">Category:
                        {% if post.category %}
                            <a href="{% url 'main:index' %}?category={{post.category.id}}">{{post.category.name}}</a>
                        {% else %}
                            None
                        {% endif %}
                        </span>

                        <span class="meta">Tags:
                        {% for tag in tags %}
                            <a href="{% url 'main:index' %}?tag={{tag.id}}">{{tag.name}}</a>{% if not forloop.last%},  {% else %}{% endif %} 
                        {% empty %}
                            None
                        {% endfor %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
<div class="container">
    <article>
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{post.content_html|safe}}
                </div>
            </div>

            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{ jiathis_share }}
                </div>
            </div>

            <br>

            {% if allow_donate %}
            <div class="row">
                <!-- donate -->
                <div class ="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <a id="btn_donate" class="btn_donate" href="#" title="Donate">
                    <i class="fa fa-usd"></i> | <i class="fa fa-jpy"></i>
                    </a>                  
                    <br>
                  <!-- weixin -->
                  <div id="donate_guide" class="donate_bar center hidden">
                      <img src="http://7tsygu.com1.z0.glb.clouddn.com/mayblog-weixin-pay.jpg?imageView/2/w/300" title="Donate">
                  </div> 
                </div>
                <!-- donate --> 
                
            </div>
            
            {% endif %}
            
        <!-- </div> -->
    </article>

    <br>


    <hr>



    <article>
        <!-- <div class="container"> -->
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{ comment_script }}
                </div>
            </div>
        <!-- </div> -->
    </article>

</div>

{% endblock %}

{% block js %}
<script type="text/javascript">
    // $('#btn_donate').on('click', function(event){
    //     $('#donate_guide').removeClass('hidden');
    //     // $(this).attr('id', 'btn_donate_hidden');
    //     return false
    // });
    $('#btn_donate').on('click', function(event){
        if($('#donate_guide').hasClass('hidden'))
            $('#donate_guide').removeClass('hidden');
        else
            $('#donate_guide').addClass('hidden');
        return false
    })
    

    
</script>
{% endblock %}

blog/templates/main/simple_form.html
{% extends "admin_base.html" %}

{% block title %}{{ title }}{% endblock %}

{% load static %}


{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
    <h3>{{ heading }}</h3>
    <hr>
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="submit">
            {% if btn_name %}
                {{ btn_name }}
            {% else %}
                submit
            {% endif %}
            </button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>

{% endblock %}