blog/accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^users/$', views.UsersView.as_view(), name='users'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/$', views.UserView.as_view(), name='user'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/edit/$', views.UserEditView.as_view(), name='user_edit'),
    url(r'^groups/(?P<group_id>[0-9]+)/users/$', views.UsersView.as_view(), name='group_users'),
    url(r'^groups/$', views.GroupsView.as_view(), name='groups'),
    url(r'^groups/(?P<pk>(-)?[0-9]+)/$', views.GroupView.as_view(), name='group'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^admin2/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

blog/accounts/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Account(models.Model):
    display_name = models.CharField(max_length=128)
    biography = models.TextField(null=True, blank=True)
    homepage = models.URLField(null=True, blank=True)
    weixin = models.URLField(null=True, blank=True)
    douban = models.URLField(null=True, blank=True)
    weibo = models.URLField(null=True, blank=True)
    twitter = models.URLField(null=True, blank=True)
    github = models.URLField(null=True, blank=True)
    user = models.OneToOneField(User)


    @receiver(post_save, sender=User)
    def create_user_account(sender, instance=None, created=False, **kwargs):
        if created:
            Account.objects.get_or_create(user=instance, defaults={'display_name':instance.username})

    def __str__(self):
        return self.display_name

@python_2_unicode_compatible
class SocialInfo(models.Model):
    SOCIAL_CHOICES = (
    ('fa-facebook', 'Facebook'),
    ('fa-github', 'Github'),
    ('fa-twitter', 'Twitter'),
    ('fa-google-plus', 'Google Plus'),
    ('fa-weibo', 'Weibo'),)
    ('fa-bookmark', 'Other'),

    user = models.ForeignKey(User)
    social = models.CharField(choices=SOCIAL_CHOICES, max_length=128)
    url = models.URLField()

    def __str__(self):
        return self.user.name + '-' + self.social

blog/accounts/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate

def group_values():
    groups = Group.objects.all()
    choices = [(group.id, group.name) for group in groups ]
    return choices

class LoginForm(forms.Form):
    username = forms.CharField(max_length=256)
    password = forms.CharField(max_length=256, widget=forms.PasswordInput)

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=256)
    email = forms.EmailField(max_length=256, required=False)
    password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=256, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password != password_confirm:
            raise forms.ValidationError('Two passwords are not the same')

class UserForm(forms.Form):
    username = forms.CharField(max_length=256)
    email = forms.EmailField(max_length=256, required=False)
    # password = forms.CharField(max_length=256, widget=forms.PasswordInput(attrs={'placeholder': 'password'}), required=False)
    # password_confirm = forms.CharField(max_length=256, widget=forms.PasswordInput)
    # is_staff = forms.BooleanField(required=False)
    # is_superuser = forms.BooleanField(required=False)

    # def clean(self):
    #     cleaned_data = super(RegisterForm, self).clean()
    #     password = cleaned_data.get('password')
    #     password_confirm = cleaned_data.get('password_confirm')
    #     if password != password_confirm:
    #         raise forms.ValidationError('Two passwords are not the same')

class UserGroupForm(forms.Form):
    # GROUP_CHOICES = group_values()
    GROUP_CHOICES = ()
    groups = forms.MultipleChoiceField(choices=GROUP_CHOICES, widget=forms.SelectMultiple(attrs={'size':len(GROUP_CHOICES)}))

    def __init__(self, *args, **kwargs):
        super(UserGroupForm, self).__init__(*args, **kwargs)
        groups = [(group.id, group.name) for group in Group.objects.all() ]
        # self.fields['groups'].choices = groups
        # self.fields['groups'].widget = forms.SelectMultiple(attrs={'size':len(groups)})
        self.fields['groups'] = forms.MultipleChoiceField(choices=groups, widget=forms.SelectMultiple(attrs={'size':len(groups)}))

class ProfileForm(forms.Form):
    display_name = forms.CharField(max_length='128')
    biography = forms.CharField(required=False, widget=forms.Textarea)
    homepage = forms.URLField(required=False)
    weixin = forms.URLField(required=False)
    douban = forms.URLField(required=False)
    weibo = forms.URLField(required=False)
    twitter = forms.URLField(required=False)
    github = forms.URLField(required=False)

class ChangePasswordForm(forms.Form):
    username = forms.CharField(max_length=256, widget=forms.HiddenInput)
    old_password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    new_password = forms.CharField(max_length=256, widget=forms.PasswordInput)
    confirm_password = forms.CharField(max_length=256, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()
        new_password = cleaned_data.get('new_password')
        confirm_password = cleaned_data.get('confirm_password')
        if new_password != confirm_password:
            raise forms.ValidationError('Two passwords are not the same')

        username = cleaned_data.get('username')
        password = cleaned_data.get('old_password')
        user = authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('username and password does not match')


    

blog/accounts/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import View
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from guardian.decorators import permission_required

from . import forms

PER_PAGE = settings.MAY_BLOG['PER_PAGE_ADMIN']

# Create your views here.
class LoginView(View):
    template_name = 'accounts/simple_form.html'
    def get(self, request, form=None):
        data = {}
        if not form:
            form = forms.LoginForm()
        data['form'] = form
        data['title'] = 'Login'
        data['btn_name'] = 'Login'
        return render(request, self.template_name, data)
    def post(self, request, form=None):
        data = {}
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    # Redirect to a success page.
                    url = request.GET.get('next', None)
                    if not url:
                        url = reverse('main:admin_index')
                    return redirect(url)
                else:
                    # Return a 'disabled account' error message
                    msg = 'The user is disabled'
                    messages.add_message(request, messages.WARNING, msg)
                    return self.get(request, form)
            else:
                # Return an 'invalid login' error message.
                msg = 'Invalid login, user does not exist'
                messages.add_message(request, messages.ERROR, msg)
                return self.get(request, form)

        else:
            return self.get(request, form)

class LogoutView(View):
    def get(self, request):
        logout(request)
        msg = 'Succeed to logout'
        url = reverse('accounts:login')
        return redirect(url)

class RegisterView(View):
    template_name = 'accounts/simple_form.html'
    def get(self, request, form=None):
        if not form:
            form = forms.RegisterForm()

        data = {'title':'Register', 'form':form, 'btn_name':'Register'}

        return render(request, self.template_name, data)

    def post(self, request):
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = User.objects.create_user(username, email, password)
            
            user.save()

            msg = 'Successfully Registered'
            messages.add_message(request, messages.SUCCESS, msg)
            url = reverse('accounts:login')
            return redirect(url)

        else:
            return self.get(request, form)

class UsersView(View):
    template_name = 'accounts/users.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, group_id=0):
        data = {}
        
        if group_id:
            group = Group.objects.get(pk=group_id)
            users = group.user_set.all()
            data['group_id'] = int(group_id)
        else:
            users = User.objects.all()
            data['all'] = True

        key = request.GET.get('key')
        if key:
            users = users.filter(username__icontains=key)

        paginator = Paginator(users, PER_PAGE)
        page = request.GET.get('page')
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            users = paginator.page(1)
        except EmptyPage:
            users = paginator.page(paginator.num_pages)

        groups = Group.objects.all()
        # data = {'users':users, 'groups':groups}
        data['users'] = users
        data['groups'] = groups

        data['allow_search'] = True

        return render(request, self.template_name, data)

class UserView(View):
    template_name = 'accounts/user.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, pk):
        pk = int(pk)
        data = {}
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        data['user'] = user

        groups = user.groups.all()
        data['groups'] = groups

        # permissions = user.get_all_permissions()
        # data['permissions'] = permissions
        permissions = user.user_permissions.all()
        data['permissions'] = permissions

        return render(request, self.template_name, data)

class GroupView(View):
    template_name = 'accounts/group.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, pk):
        pk = int(pk)
        data = {}
        try:
            group = Group.objects.get(pk=pk)
        except group.DoesNotExist:
            raise Http404
        data['group'] = group

        permissions = group.permissions.all()
        data['permissions'] = permissions

        users = group.user_set.all()
        data['users'] = users

        return render(request, self.template_name, data)

class UserEditView(View):
    template_name = 'accounts/user_edit.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request, pk, user_form=None):
        pk = int(pk)
        data = {}
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        
        data['user_edited'] = user

        user_dict = {'username':user.username, 'email': user.email}
        if not user_form:
            user_form = forms.UserForm(initial=user_dict)
        data['user_form'] = user_form

        groups = user.groups.all()
        user_groups = [group.id for group in groups ]
        group_dict = {'groups':user_groups}
        user_group_form = forms.UserGroupForm(initial=group_dict)
        data['user_group_form'] = user_group_form

        return render(request, self.template_name, data)

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def post(self, request, pk):
        pk = int(pk)
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            raise Http404
        if request.POST.get('user'):
            form = forms.UserForm(request.POST)
            if form.is_valid():
                user.username = form.cleaned_data['username']
                user.email = form.cleaned_data['email']
                if request.user.is_superuser:
                    user.is_superuser = request.POST.get('is_superuser', False)
                    user.is_staff = request.POST.get('is_staff', False)
                user.save()

                url = reverse('accounts:user_edit', args=(pk,))
                msg = 'Succeed to update user details'
                messages.add_message(request, messages.SUCCESS, msg)
                return redirect(url)

            return self.get(request, pk, user_form=form)
        else:
            group_ids = request.POST.getlist('groups')
            # user.groups.add(*group_ids)
            user.groups = group_ids
            # return HttpResponse(group_ids)
            url = reverse('accounts:user_edit', args=(pk,))
            msg = 'Succeed to update user groups'
            messages.add_message(request, messages.SUCCESS, msg)
            return redirect(url)


class GroupsView(View):
    template_name = 'accounts/groups.html'

    @method_decorator(permission_required('main.change_user', accept_global_perms=True))
    def get(self, request):
        groups = Group.objects.all()
        data = {'groups':groups}

        return render(request, self.template_name, data)

class ProfileView(View):
    template_name = 'accounts/settings_profile.html'

    @method_decorator(login_required)
    def get(self, request, form=None):
        data = {}
        form_data = {
            'display_name' : request.user.account.display_name,
            'biography' : request.user.account.biography,
            'homepage' : request.user.account.homepage,
            'weixin' : request.user.account.weixin,
            'douban' : request.user.account.douban,
            'weibo' : request.user.account.weibo,
            'twitter' : request.user.account.twitter,
            'github' : request.user.account.github
        }

        if not form:
            form = forms.ProfileForm(initial=form_data)

        data['form'] = form
        data['is_profile'] = True

        return render(request, self.template_name, data)

    @method_decorator(login_required)
    def post(self, request):
        form = forms.ProfileForm(request.POST)
        if form.is_valid():
            account = request.user.account

            account.display_name = form.cleaned_data['display_name']
            account.biography = form.cleaned_data['biography']
            account.homepage = form.cleaned_data['homepage']
            account.weixin = form.cleaned_data['weixin']
            account.douban = form.cleaned_data['douban']
            account.weibo = form.cleaned_data['weibo']
            account.twitter = form.cleaned_data['twitter']
            account.github = form.cleaned_data['github']

            account.save()

            msg = 'Succeed to update profile'

blog/templates/accounts/group.html
{% extends 'admin_base.html' %}

{% block main %}
<div class="row">
  <div class="col-md-9">
    <div class="row">
        <h4>Group Details &nbsp; 
            <small><a href="#"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
        </h4>
        <hr>
        <p><label>Name</label>: {{ group.name }}</p>
    </div>
    <div class="row">
        <h4>Users</h4>
        <hr>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Is Active</th>
                    <th>Last Login</th>
                    <th>Create Date</th>
                    <th style="text-align:center">Remove out</th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr id="user-{{ user.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'accounts:user' user.id %}">{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.is_active }}</td>
                    <td>{{ user.last_login|date:"M d, Y" }}</td>
                    <td>{{ user.date_joined|date:"M d, Y" }}</td>
                    <td style="text-align:center">
                        <!-- <a href="{% url 'accounts:user_edit' user.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                        &nbsp -->
                        <a href="#"  class="remove-user"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span> </a>
                    </td>
                </tr>
                {% empty %}
                <tr><td colspan="7">No user yet</td></tr>
            {% endfor %}     
            </tbody>
        </table>
    </div>
  </div>
    <div class="col-md-2 col-md-offset-1">
    <h4>Permissions</h4>
    <hr>
    <ul class="list-group">
        {% for permission in permissions %}
            <li class="list-group-item group-list">{{ permission.name }}</li>
        {% empty %}
            <p>No permission yet!</p>
        {% endfor %}
    </ul>
  </div>

</div>
{% endblock %}

blog/templates/accounts/groups.html
{% extends "admin_base.html" %}
{% block title %}Groups{% endblock %}

{% block main %}

<div class="row">
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Group Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr id="group-{{ group.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'accounts:group' group.id %}">{{ group.name }}</td>
                <td>
                    <a href="#"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% empty %}
            <tr><td colspan="7">No group yet</td></tr>
        {% endfor %}     
        </tbody>
    </table>


    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}


blog/templates/accounts/login.html
{% extends "admin_base.html" %}

{% block title %}Login{% endblock %}


{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        <form method="POST" action="" id='login'>
        {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="login">Login</button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>

{% endblock %}

blog/templates/accounts/settings_profile.html
{% extends 'admin_base.html' %}

{% block title %}Profile{% endblock %}

{% block main %}
{% load bootstrap3 %}

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="nav nav-tabs">
            <li role="presentation" {% if is_profile %} class="active" {% endif %}><a href="{% url 'accounts:profile' %}">Profile</a></li>
            <li role="presentation" {% if is_password %} class="active" {% endif %}onkeyup=""><a href="{% url 'accounts:change_password' %}">Password</a></li>
        </ul>
        
        <br>

        <div class="col-md-10 col-md-offset-1">
        <form method="POST" action="">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="submit">submit</button>
        </form>
        </div>

    </div>
</div>
{% endblock %}

blog/templates/accounts/simple_form.html
{% extends "admin_base.html" %}

{% block title %}{{ title }}{% endblock %}


{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-xs-6 col-sm-3"></div>
    <div class="col-xs-6 col-sm-6">
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary" name="login">
            {% if btn_name %}
                {{ btn_name }}
            {% else %}
                submit
            {% endif %}
            </button>
        </form>
    </div>
    <div class="col-xs-6 col-sm-3"></div>
</div>

{% endblock %}

blog/templates/accounts/user.html
{% extends 'admin_base.html' %}

{% block main %}
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <h4>User Details &nbsp; 
        <small><a href="{% url 'accounts:user_edit' user.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
    </h4>
    <hr>
    <p><label>Username</label>: {{ user.username }}</p>
    <p><label>Email:</label> {{ user.email }}</p>
    <p><label>Is active:</label> {{ user.is_active}} </p>
    <p><label>Is staff:</label> {{ user.is_staff}} </p>
    <p><label>Is superuser:</label> {{ user.is_superuser}} </p>
    <p><label>Last Login:</label> {{ user.last_login}}</p>
    <p><label>Create time:</label> {{ user.date_joined }}</p>
  </div>
  <div class="col-md-2">
    <h4>User Groups</h4>
    <hr>
    <ul class="list-group">
        {% for group in groups %}
            <li class="list-group-item group-list"><a href='#'>{{ group.name }}</a></li>
        {% empty %}
            <p>No group yet!</p>
        {% endfor %}
    </ul>
  </div>
    <div class="col-md-2">
    <h4>User Permissions</h4>
    <hr>
    <ul class="list-group">
        {% for permission in permissions %}
            <li class="list-group-item group-list">{{ permission.name }}</li>
        {% empty %}
            <p>No permission yet!</p>
        {% endfor %}
    </ul>
  </div>

</div>{% endblock %}

blog/templates/accounts/user_edit.html
{% extends 'admin_base.html' %}
{% block title %} Edit User {% endblock %}

{% load bootstrap3 %}

{% block main %}
<div class="row">
    <div class="col-md-6 col-md-offset-1">
        <h3>User Details</h3>
        <hr>
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form user_form %}
            {% if user.is_superuser %}
            <div class="checkbox">
                <label>
                  <input type="checkbox" name="is_superuser" {% if user_edited.is_superuser %}checked{% endif %}> is_superuser
                </label>
            </div>
            <div class="checkbox">
                <label>
                  <input type="checkbox" name="is_staff" {% if user_edited.is_staff %}checked{% endif %}> is_staff
                </label>
            </div>
            {% endif %}
            <button type="submit" class="btn btn-primary" name="user" value="user">Submit</button>
        </form>
    </div>
    <div class="col-md-4">
        <h3>Groups</h3>
        <hr>
        <form method="POST" action="">
        {% csrf_token %}
            {% bootstrap_form user_group_form %}{{groups}}
            <button type="submit" class="btn btn-primary" name="group" value="group">Submit</button>
        </form>
    </div>

</div>

{% endblock %}

blog/templates/accounts/users.html
{% extends "admin_base.html" %}
{% block title %}Users{% endblock %}

{% block main %}
{% load bootstrap3 %}
<div class="row">
    <div class="col-md-10">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Username</th>
                <th>Email</th>
                <th>Is Active</th>
                <th>Last Login</th>
                <th>Create Date</th>
                <th>Actions</th>
            </tr>
    </thead>
    <tbody>
    {% for user in users %}
        <tr id="user-{{ user.id }}">
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'accounts:user' user.id %}">{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_active }}</td>
            <td>{{ user.last_login|date:"M d, Y" }}</td>
            <td>{{ user.date_joined|date:"M d, Y" }}</td>
            <td>
                <a href="{% url 'accounts:user_edit' user.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                &nbsp
                <a href="#"  class="del-user"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
            </td>
        </tr>
        {% empty %}
        <tr><td colspan="7">No user yet</td></tr>
    {% endfor %}     
    </tbody>
    </table>

    {% bootstrap_pagination users %}

    </div>
    <div class="col-md-2">
        <!-- <h4>Filter By Group</h4> -->
        <p><strong>Filter By Group</strong></p>
        <hr>
        <div class="list-group">
          <a href="{% url 'accounts:users' %}" class="list-group-item group-list {% if all %}active{% endif %}">All</a>
          {% for group in groups %}
            <a href="{% url 'accounts:group_users' group.id %}" class="list-group-item group-list {% if group_id == group.id %}active{% endif %}">{{ group.name }}</a>
          {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-user').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');

    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        $.get(url, function(){
            location.reload();
        });
        }

    });
    return false;
  });
</script>
{% endblock %}