blog/accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^users/$', views.UsersView.as_view(), name='users'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/$', views.UserView.as_view(), name='user'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/edit/$', views.UserEditView.as_view(), name='user_edit'),
    url(r'^groups/(?P<group_id>[0-9]+)/users/$', views.UsersView.as_view(), name='group_users'),
    url(r'^groups/$', views.GroupsView.as_view(), name='groups'),
    url(r'^groups/(?P<pk>(-)?[0-9]+)/$', views.GroupView.as_view(), name='group'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^admin2/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

blog/main/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from . import views, preblog, feeds, sitemaps


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.Post.as_view(), name='post'),
    url(r'^page/(?P<pk>[0-9]+)/$', views.Page.as_view(), name='page'),
    url(r'^archive$', views.Archive.as_view(), name='archive'),
    url(r'^authors/(?P<pk>[0-9]+)/$', views.Author.as_view(), name='author'),
]

urlpatterns += [
    url(r'^admin/$', views.AdminIndex.as_view(), name='admin_index'),
    url(r'^admin/meta$', views.AdminBlogMeta.as_view(), name='admin_blog_meta'),
    url(r'^admin/posts$', views.AdminPosts.as_view(), name='admin_posts'),
    url(r'^admin/pages$', views.AdminPosts.as_view(), {'is_blog_page':True}, name='admin_pages'),
    url(r'^admin/post$', views.AdminPost.as_view(), name='admin_post'),
    url(r'^admin/page$', views.AdminPage.as_view(), name='admin_page'),
    url(r'^admin/posts/(?P<pk>[0-9]+)$', views.AdminPost.as_view(), name='admin_edit_post'),
    url(r'^admin/pages/(?P<pk>[0-9]+)$', views.AdminPage.as_view(), name='admin_edit_page'),
    url(r'^admin/posts/delete/(?P<pk>[0-9]+)$', views.DeletePost.as_view(), name='admin_delete_post'),
    url(r'^admin/pages/delete/(?P<pk>[0-9]+)$', views.DeletePage.as_view(), name='admin_delete_page'),
    url(r'^admin/tags/$', views.AdminTags.as_view(), name='admin_tags'),
    url(r'^admin/category/$', views.AdminCategory.as_view(), name='admin_category'),
    url(r'^admin/filter-posts$', views.AdminFilterPosts.as_view(), name='admin_filter_posts'),
    url(r'^admin/tags/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'tag'}, name='admin_delete_tag'),
    url(r'^admin/categories/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'category'}, name='admin_delete_category'),
    url(r'^admin/tags/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'tag'}, name='admin_edit_tag'),
    url(r'^admin/categories/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'category'}, name='admin_edit_category'),
]

urlpatterns += [
    url(r'^init$', preblog.BlogInitView.as_view()),
    url(r'^reinit-meta$', preblog.ReInitBlogMetaView.as_view()),
    url(r'^rss/$', feeds.LatestEntriesFeed2(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps.sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/main/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
import markdown2

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=256, default='new blog')
    abstract = models.TextField(null=True, blank=True)
    raw = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    content_html = models.TextField(null=True, blank=True)
    author = models.ForeignKey(User)
    tags = models.ManyToManyField('Tag', blank=True)
    category = models.ForeignKey('Category', null=True, blank=True)
    is_draft = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post', kwargs={ 'pk': self.id })

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Page(models.Model):
    title = models.CharField(max_length=256, default='new page')
    slug = models.CharField(max_length=256, default='slug')
    raw = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    content_html = models.TextField()
    author = models.ForeignKey(User)
    is_draft = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:page', kwargs={ 'pk': self.id })

@python_2_unicode_compatible
class BlogMeta(models.Model):
    key = models.CharField(max_length=256)
    value = models.CharField(max_length=256, null=True, blank=True)
    flag = models.BooleanField(default=False)
    misc = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.key

blog/templates/admin_base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}May Blog Admin{% endblock %}</title>

    {% load static %}
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">
    
    <!-- Bootstrap Core CSS -->

    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/mayblog.css' %} " rel="stylesheet">
    {# Load the tag library #}
    {% load bootstrap3 %}


    
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages FIXTHIS %}

    <!-- Custom CSS -->
    <!-- <link href="{% static 'css/clean-blog.min.css' %} " rel="stylesheet"> -->
    {% block css %}{% endblock %}

    <!-- Custom Fonts -->
    <!-- <link href="http://libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'main:index' %}">Blog Admin</a>
        </div>

        {% if request.user.is_authenticated %}
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="_active"><a href="{% url 'main:admin_index' %}">Home <span class="sr-only">(current)</span></a></li>
            <!-- <li><a href="#">Link</a></li> -->
            {% if perms.main.add_post %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Posts <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'main:admin_posts' %}">All Posts</a></li>
                <li><a href="{% url 'main:admin_post' %}">New Post</a></li>
                <li><a href="{% url 'main:admin_posts' %}?draft=true">Drafts</a></li>
                {% if perms.main.add_tag %}
                <li class="divider"></li>
                <li><a href="{% url 'main:admin_tags' %}">Tags</a></li>
                {% endif %}

                {% if perms.main.add_category %}
                <li class="divider"></li>
                <li><a href="{% url 'main:admin_category' %}">Category</a></li>
                {% endif %}
              </ul>
            </li>
            {% endif %}
            {% if perms.main.add_page %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pages <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'main:admin_pages' %}">All Pages</a></li>
                <li><a href="{% url 'main:admin_page' %}">New Page</a></li>
                <li><a href="{% url 'main:admin_pages' %}?draft=true">Drafts</a></li>
              </ul>
            </li>
            {% endif %}
            {% if perms.auth.add_user %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'accounts:users' %}">All Users</a></li>
                <li><a href="{% url 'accounts:register' %}">New User</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'accounts:groups' %}">User Groups</a></li>
                <!-- <li class="divider"></li>
                <li><a href="#">Category</a></li> -->
              </ul>
            </li>
            {% endif %}
          </ul>
          
          <ul class="nav navbar-nav navbar-right">
          {% if allow_search %}
            <form class="navbar-form navbar-left" role="search" method="get">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search" name="key">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
          {% endif %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user.username }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'accounts:profile' %}">Settings</a></li>
                <!-- <li><a href="#">Another action</a></li> -->
                <!-- <li><a href="#">Something else here</a></li> -->
                <li class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Exit</a></li>
              </ul>
            </li>
          </ul>

        </div><!-- /.navbar-collapse -->
        {% else %}
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:register' %}">Register</a></li>
          </ul>
        </div>
        {% endif %}
      </div><!-- /.container-fluid -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}

    <div class="container">
        <!-- Main Content -->

        
        {%block main %}{% endblock %}

    </div>

    <hr>

    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'main:rss' %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/flyhigher139/mayblog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted text-center">Copyright &copy; May Blog 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/bootbox.js/4.4.0/bootbox.min.js"></script>
    

    <!-- Custom Theme JavaScript -->
    {% block js %}
    {% endblock %}
    

</body>

</html>

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="title" content="{{ seo.title }}">
    <meta name="description" content="{{ seo.desc }}">
    <meta name="author" content="{{ seo.author }}">
    <meta name="keywords" content="{{ seo.keywords }}">
    <meta name="google-site-verification" content="{{ seo.google_verify }}">
    <meta name="baidu-site-verification" content="{{ seo.baidu_verify }}">


    <title>{% block title %}May Blog{% endblock %}</title>

    {% load static %}
    <!-- Bootstrap Core CSS -->

    <!-- <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"> -->
    <!-- <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"> -->

    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}">

    <!-- <link href="http://cdn.staticfile.org/twitter-bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://cdn.staticfile.org/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"> -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <link href="//cdn.bootcss.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.css' %} " rel="stylesheet">
    <link href="{% static 'css/mayblog.css' %} " rel="stylesheet">
    <link rel="stylesheet" href="http://cdn.staticfile.org/highlight.js/8.3/styles/default.min.css">

    <!-- Custom Fonts -->
    <!-- <link href="http://libs.useso.com/js/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main:index' %}">May Blog</a> 

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'main:rss' %}">RSS</i></a>
                    </li>
                    <li>
                        <a href="{% url 'main:archive' %}">Archive</i></a>
                    </li>
                    {% for page in pages %}
                    <li>
                        <a href="{% url 'main:page' page.id %}">{{ page.slug }}</a>
                    </li>
                    {% endfor %}
                    {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'main:admin_index' %}">{{ request.user.username }}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {%block header %}{% endblock %}

    <!-- Main Content -->
    {%block main %}{% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://creativecommons.org/licenses/" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-creative-commons fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'main:rss' %}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-rss fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/flyhigher139/mayblog" target="_blank">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; May Blog 2015</p>
                    <p class="copyright text-muted"><a href="http://www.qiniu.com" target="_blank" ><img src="http://assets.qiniu.com/qiniu-transparent.png"></a></p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="//cdn.bootcss.com/jquery/2.1.4/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{# static 'js/clean-blog.min.js' #}"></script>
    <script src="//cdn.bootcss.com/highlight.js/8.7/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    {% block js %}
    {% endblock %}

</body>

</html>