blog/accounts/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile/password/$', views.ChangePasswordView.as_view(), name='change_password'),
    url(r'^users/$', views.UsersView.as_view(), name='users'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/$', views.UserView.as_view(), name='user'),
    url(r'^users/(?P<pk>(-)?[0-9]+)/edit/$', views.UserEditView.as_view(), name='user_edit'),
    url(r'^groups/(?P<group_id>[0-9]+)/users/$', views.UsersView.as_view(), name='group_users'),
    url(r'^groups/$', views.GroupsView.as_view(), name='groups'),
    url(r'^groups/(?P<pk>(-)?[0-9]+)/$', views.GroupView.as_view(), name='group'),
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
# ]

urlpatterns = [
    url(r'^admin2/', include(admin.site.urls)),
    url(r'^', include('main.urls', namespace='main')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
]

blog/main/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap

from . import views, preblog, feeds, sitemaps


urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.Post.as_view(), name='post'),
    url(r'^page/(?P<pk>[0-9]+)/$', views.Page.as_view(), name='page'),
    url(r'^archive$', views.Archive.as_view(), name='archive'),
    url(r'^authors/(?P<pk>[0-9]+)/$', views.Author.as_view(), name='author'),
]

urlpatterns += [
    url(r'^admin/$', views.AdminIndex.as_view(), name='admin_index'),
    url(r'^admin/meta$', views.AdminBlogMeta.as_view(), name='admin_blog_meta'),
    url(r'^admin/posts$', views.AdminPosts.as_view(), name='admin_posts'),
    url(r'^admin/pages$', views.AdminPosts.as_view(), {'is_blog_page':True}, name='admin_pages'),
    url(r'^admin/post$', views.AdminPost.as_view(), name='admin_post'),
    url(r'^admin/page$', views.AdminPage.as_view(), name='admin_page'),
    url(r'^admin/posts/(?P<pk>[0-9]+)$', views.AdminPost.as_view(), name='admin_edit_post'),
    url(r'^admin/pages/(?P<pk>[0-9]+)$', views.AdminPage.as_view(), name='admin_edit_page'),
    url(r'^admin/posts/delete/(?P<pk>[0-9]+)$', views.DeletePost.as_view(), name='admin_delete_post'),
    url(r'^admin/pages/delete/(?P<pk>[0-9]+)$', views.DeletePage.as_view(), name='admin_delete_page'),
    url(r'^admin/tags/$', views.AdminTags.as_view(), name='admin_tags'),
    url(r'^admin/category/$', views.AdminCategory.as_view(), name='admin_category'),
    url(r'^admin/filter-posts$', views.AdminFilterPosts.as_view(), name='admin_filter_posts'),
    url(r'^admin/tags/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'tag'}, name='admin_delete_tag'),
    url(r'^admin/categories/delete/(?P<pk>[0-9]+)$', views.simple_delete, {'flag':'category'}, name='admin_delete_category'),
    url(r'^admin/tags/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'tag'}, name='admin_edit_tag'),
    url(r'^admin/categories/edit/(?P<pk>[0-9]+)$', views.simple_update, {'flag':'category'}, name='admin_edit_category'),
]

urlpatterns += [
    url(r'^init$', preblog.BlogInitView.as_view()),
    url(r'^reinit-meta$', preblog.ReInitBlogMetaView.as_view()),
    url(r'^rss/$', feeds.LatestEntriesFeed2(), name='rss'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps.sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/main/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible
import markdown2

# Create your models here.

@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(max_length=256, default='new blog')
    abstract = models.TextField(null=True, blank=True)
    raw = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    content_html = models.TextField(null=True, blank=True)
    author = models.ForeignKey(User)
    tags = models.ManyToManyField('Tag', blank=True)
    category = models.ForeignKey('Category', null=True, blank=True)
    is_draft = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:post', kwargs={ 'pk': self.id })

@python_2_unicode_compatible
class Tag(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=256)

    def __str__(self):
        return self.name

@python_2_unicode_compatible
class Page(models.Model):
    title = models.CharField(max_length=256, default='new page')
    slug = models.CharField(max_length=256, default='slug')
    raw = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    content_html = models.TextField()
    author = models.ForeignKey(User)
    is_draft = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.content_html = markdown2.markdown(self.raw, extras=['code-friendly', 'fenced-code-blocks']).encode('utf-8')
        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('main:page', kwargs={ 'pk': self.id })

@python_2_unicode_compatible
class BlogMeta(models.Model):
    key = models.CharField(max_length=256)
    value = models.CharField(max_length=256, null=True, blank=True)
    flag = models.BooleanField(default=False)
    misc = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.key

blog/main/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

class NewPost(forms.Form):
    title = forms.CharField(max_length=256)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))
    abstract = forms.CharField(widget=forms.Textarea(attrs={'rows':4}), required=False)
    author_id = forms.IntegerField(required=False, widget=forms.HiddenInput)
    # tag = forms.CharField(max_length=256, required=False)
    # category = forms.CharField(max_length=256, required=False)

class NewPage(forms.Form):
    title = forms.CharField(max_length=256)
    slug = forms.CharField(max_length=64)
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':20}))
    author_id = forms.IntegerField(required=False, widget=forms.HiddenInput)

class CategoryForm(forms.Form):
    name = forms.CharField(max_length=256, label='Category Name')

class TagForm(forms.Form):
    tags = forms.CharField(max_length=256, label='Tags')

class BlogMetaForm(forms.Form):
    title = forms.CharField(max_length=256, label='Title')
    subtitle = forms.CharField(max_length=256, label='SubTitle')
    desc = forms.CharField(max_length=256, label='Description')
    author = forms.CharField(max_length=256, label='Owner')
    keywords = forms.CharField(max_length=256, label='Keywords')
    google_verify = forms.CharField(max_length=256, label='Google Site Verification', required=False)
    baidu_verify = forms.CharField(max_length=256, label='Baidu Site Verification', required=False)

blog/templates/blog_admin/catagory.html
{% extends "admin_base.html" %}
{% block title %}Admin Catagory{% endblock %}

{% block main %}
{% load bootstrap3 %}
<div class="row">
    <!-- <div class="col-md-10"> -->
    <!-- <h1>New Post</h1> -->
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for catagory in catagories %}
            <tr id="post-{{ catagory.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'main:admin_filter_posts' %}?catagory={{ catagory.id }}">{{ catagory.name }}</a></td>
                <td>
                    <a href="#" class="edit-tag"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                    &nbsp
                    <a href="#"  class="del-tag"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% bootstrap_pagination catagories %}

    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-post').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;

    bootbox.confirm("Are you sure?", function(result) {
      // url = $('#del-post').attr('href');
      url = event.target.href;

      // alert(url);
      if(result){
        $.get(url, function(){
            location.reload();
        });
        }

    });
    return false;
  });
</script>
{% endblock %}

blog/templates/blog_admin/category.html
{% extends "admin_base.html" %}
{% block title %}Admin Category{% endblock %}

{% block main %}

{% load bootstrap3 %}

<div class="row">
    <!-- <div class="col-md-10 col-md-offset-1"> -->
        <form class="form-inline" method="POST" >
        {% csrf_token %}                
                    
            {% bootstrap_form form %}

            <button type="submit" class="btn btn-primary" name="publish" value="publish">Create</button>
        </form>
    <!-- </div> -->


</div>

<hr>

<div class="row">

    <!-- <div class="col-md-10 col-md-offset-1"> -->
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>No.</th>
                    <th>name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for category in catagories %}
                <tr id="post-{{ category.id }}">
                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'main:admin_filter_posts' %}?category={{ category.id }}">{{ category.name }}</a></td>
                    <td>
                        <a href="{% url 'main:admin_edit_category' category.id %}" class="edit-category" data-name='{{ category.name }}'><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                        &nbsp
                        <a href="{% url 'main:admin_delete_category' category.id %}" class="del-category"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        {% bootstrap_pagination catagories %}

    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-category').on('click', function (event) {
    id = $(this).data('id')
    var url = $(this).attr('href');
    bootbox.confirm("Are you sure?", function(result) {
        if(result){
            $.ajax({
                url: url,
                type: 'GET',
                success: function(result){
                    location.reload();
                }
            });
        }

    });
    return false;
  });

$('.edit-category').on('click', function (event){
    var url = $(this).attr('href');
    var name = $(this).data('name')
    bootbox.prompt({
        title: "Update category",
        value: name,
        callback: function(result) {
            if (result === null) {
              return;
            } else {
              $.ajax({
                url:url,
                type: 'GET',
                data: {'name': result},
                success: function(result2){
                    location.reload();
                }
              });
            }
        }
    });
    return false;
});

</script>
{% endblock %}

blog/templates/blog_admin/index.html
{% extends 'admin_base.html' %}
{% block title %}May Blog Admin {% endblock %}

{%block main %}

<div class="col-md-8 col-md-offset-2">
    <div class="row">
        <h3>
            Blog Meta Data &nbsp;
            {% if perms.main.change_blogmeta %}
            <small><a href="{% url 'main:admin_blog_meta' %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
            {% endif %}
        </h3>
        <hr>
        <dl class="dl-horizontal">
            <dt>Blog Name:</dt>
            <dd>{{ site_info.title }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Subtitle:</dt>
            <dd>{{ site_info.subtitle }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Description:</dt>
            <dd>{{ site_info.desc }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Owner:</dt>
            <dd>{{ site_info.author }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Blog Keywords:</dt>
            <dd>{{ site_info.keywords }}</dd>
        </dl>
    </div>
    <div class="row">
        <h3>
            About User &nbsp;
            <small><a href="{% url 'accounts:profile' %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a></small>
        </h3>
        <hr>
        <dl class="dl-horizontal">
            <dt>Username Name:</dt>
            <dd>{{account_info.username}}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Display Name:</dt>
            <dd>{{account_info.display_name}}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Biography:</dt>
            <dd>{{account_info.biography}}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Social Network:</dt>
            <dd>
                {% if account_info.github %}
                    <a href='{{ account_info.github }}'><i class="fa fa-github fa-lg"></i></a>
                {% endif %}

                {% if account_info.twitter %}
                    <a href='{{ account_info.twitter }}'><i class="fa fa-twitter fa-lg"></i></a>
                {% endif %}

                {% if account_info.weibo %}
                    <a href='{{ account_info.weibo }}'><i class="fa fa-weibo fa-lg"></i></a>
                {% endif %}

            </dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>Homepage:</dt>
            <dd>
                {% if account_info.homepage %}
                <a href="{{ account_info.homepage }}"><i class="fa fa-home fa-lg"></i></a> {{ account_info.homepage }}
                {% endif %}
            </dd>
        </dl>
    </div>
</div>

{% endblock %}

blog/templates/blog_admin/page.html
{% extends "admin_base.html" %}
{% load static %}

{% block title %}
    {% if edit_flag %}
        Edit Post
    {% else %}
        New Post
    {% endif %}
{% endblock %}

{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.5/css/bootstrap-select.min.css" rel="stylesheet">
{% endblock %}


{% block main %}
{% load bootstrap3 %}
<form method="POST" action="" id='new-post'>
{% csrf_token %}
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
        
        {% bootstrap_form form %}

        <button type="submit" class="btn btn-primary" name="publish" value="publish">Publish</button>
        <button type="submit" class="btn btn-success" name="draft" value="draft">Save draft</button>
        <!-- <button type="submit" class="btn btn-default" name="preview" value="draft">Preview</button> -->

        </div>
        <div class="col-md-1"></div>
    </div>
</form>
{% endblock %}


{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.5/js/bootstrap-select.min.js"></script>
{% endblock %}

blog/templates/blog_admin/pages.html
{% extends "admin_base.html" %}
{% block title %}Posts{% endblock %}

{% block main %}
{% load bootstrap3 %}
<div class="row">
    <!-- <div class="col-md-10"> -->
    <!-- <h1>New Post</h1> -->
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Title</th>
                <th>Slug</th>
                <th>Author</th>
                <th>Publish Date</th>
                <th>Update Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr id="post-{{ post.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'main:page' post.id %}" target="_blank">{{ post.title }}</td>
                <td>{{ post.slug }}</td>
                <td>{{ post.author }}</td>
                <td>{{ post.pub_time }}</td>
                <td>{{ post.update_time }}</td>
                <td>
                    <a href="{% url 'main:admin_edit_page' post.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                    &nbsp
                    <a href="{% url 'main:admin_delete_page' post.id %}"  class="del-post"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% empty %}
            <tr><td colspan="7" style="text-align: left">No pages yet</td></tr>
            {% endfor %}
         
        </tbody>
    </table>

    {% bootstrap_pagination posts %}

    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-post').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');

    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        $.get(url, function(){
            location.reload();
        });
        }

    });
    return false;
  });
</script>
{% endblock %}

blog/templates/blog_admin/post.html
{% extends "admin_base.html" %}
{% load static %}

{% block title %}
    {% if edit_flag %}
        Edit Post
    {% else %}
        New Post
    {% endif %}
{% endblock %}

{% block css %}
<link href="http://cdn.staticfile.org/bootstrap-select/1.6.3/css/bootstrap-select.min.css" rel="stylesheet">
{% endblock %}


{% block main %}
{% load bootstrap3 %}
<form method="POST" action="" id='new-post'>
{% csrf_token %}
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="row">
                {% bootstrap_form form %}
            </div>
        
            <div class="row">
                <div class="col-md-5">
                    <h3>Tags</h3>
                    <hr>
                    <select multiple class="selectpicker" name="tags">
                        {% for tag in tags %}
                        <option value="{{ tag.id }}" {% if tag in posted_tags %} selected="selected" {% endif %} >
                            {{ tag.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                

                <div class="col-md-5">
                    <h3>Category</h3>
                        <hr>
                        <select class="selectpicker" name="category">
                            {% for category in catagories %}
                            <option value="{{ category.id }}" {% if category == posted_category %} selected="selected" {% endif %} >
                                {{ category.name }}</option>
                            {% endfor %}
                    </select>
                </div>
            </div>
            <br><br><br><br>
            <div class="row">
                {% if perms.main.add_tag %}
                <!-- { #contributors can not create new tag, but writer can# } -->
                <button type="submit" class="btn btn-primary" name="publish" value="publish">Publish</button>
                {% endif %}
                <button type="submit" class="btn btn-success" name="draft" value="draft">Save draft</button>
                <button type="submit" class="btn btn-default" name="preview" value="preview" id="btn-preview">Preview</button>
            </div>
        
        </div>
    </div>

            

    

</form>
{% endblock %}


{% block js %}
<script src="http://cdn.staticfile.org/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
<script type="text/javascript">
    // using jQuery
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });

    $('#btn-preview').on('click', function(event){
        // alert('preview clicked');
        var pk = {{ pk }};
        var post_url = '';
        if(pk == 0)
            post_url = "{% url 'main:admin_post' %}";
        else
            post_url = "{% url 'main:admin_edit_post' pk %}";

        // alert(post_url);

        $.ajax({
            url: post_url,
            type: 'POST',
            data: {
                    title: $('#id_title').val(),
                    content: $('#id_content').val(),
                    abstract: $('#id_abstract').val(),
                    preview: 'preview'

                },
            success: function(data){
                pk = $.trim(data);
                url = "{% url 'main:post' pk %}";
                window.open(url, '_blank');

            },
            async: false
          });
        event.preventDefault();
        return false
    });
</script>
{% endblock %}

blog/templates/blog_admin/posts.html
{% extends "admin_base.html" %}
{% block title %}Posts{% endblock %}

{% block main %}
{% load bootstrap3 %}
<div class="row">
    <!-- <div class="col-md-10"> -->
    <!-- <h1>New Post</h1> -->
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>Title</th>
                <th>Abstract</th>
                <th>Author</th>
                <th>Publish Date</th>
                <th>Update Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr id="post-{{ post.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'main:post' post.id %}" target="_blank">{{ post.title }}</td>
                <td>{{ post.abstract }}</td>
                <td>{{ post.author.account.display_name }}</td>
                <td>{{ post.pub_time }}</td>
                <td>{{ post.update_time }}</td>
                <td>
                    <a href="{% url 'main:admin_edit_post' post.id %}"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                    &nbsp
                    <a href="{% url 'main:admin_delete_post' post.id %}"  class="del-post"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% empty %}
            <tr><td colspan="7" style="text-align: left">No posts yet</td></tr>
            {% endfor %}      
        </tbody>
    </table>

    {% bootstrap_pagination posts %}

    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-post').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    var url = $(this).attr('href');

    bootbox.confirm("Are you sure?", function(result) {
      if(result){
        $.get(url, function(){
            location.reload();
        });
        }

    });
    return false;
  });
</script>
{% endblock %}

blog/templates/blog_admin/tags.html
{% extends "admin_base.html" %}
{% block title %}Admin Tags{% endblock %}

{% block main %}
{% load bootstrap3 %}

<div class="row">
    <!-- <div class="col-md-10 col-md-offset-1"> -->
    <form class="form-inline" method="POST" >
    {% csrf_token %}                
                
        {% bootstrap_form form %}        

        <button type="submit" class="btn btn-primary" name="publish" value="publish">Create</button>
        <em>(Seperate tags with ",")</em>
    </form>
    <!-- </div> -->
        


</div>

<hr>

<div class="row">
    <!-- <div class="col-md-10"> -->
    <!-- <h1>New Post</h1> -->
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>No.</th>
                <th>name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for tag in tags %}
            <tr id="post-{{ tag.id }}">
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'main:admin_filter_posts' %}?tag={{ tag.id }}">{{ tag.name }}</a></td>
                <td>
                    <a href="{% url 'main:admin_edit_tag' tag.id %}" class="edit-tag" data-name={{ tag.name }}><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> </a>
                    &nbsp
                    <a href="{% url 'main:admin_delete_tag' tag.id %}" class="del-tag" data-id={{ tag.id }} ><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    {% bootstrap_pagination tags %}

    <!-- </div> -->
    <!-- <div class="col-md-2">.col-md-2</div> -->
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
$('.del-tag').on('click', function (event) {
    // var answer = confirm("Delete post?");
    // return answer;
    id = $(this).data('id')
    var url = $(this).attr('href');
    bootbox.confirm("Are you sure?", function(result) {
        if(result){
            // $.ajax({
            //     url: url,
            //     type: 'DELETE',
            //     crossDomain: false,
            //     beforeSend: function(xhr){
            //         xhr.setRequestHeader("Authorization",
            //             "Basic " + btoa('gevin' + ":" + 'gevin'));
            //     },

            //     success: function(result) {
            //         location.reload();
            //     }
            // });
            $.ajax({
                url: url,
                type: 'GET',
                success: function(result){
                    location.reload();
                }
            });
        }

    });
    return false;
  });

$('.edit-tag').on('click', function (event){
    var url = $(this).attr('href');
    var name = $(this).data('name')
    bootbox.prompt({
        title: "Update tag",
        value: name,
        callback: function(result) {
            if (result === null) {
              return;
            } else {
              $.ajax({
                url:url,
                type: 'GET',
                data: {'name': result},
                success: function(result2){
                    location.reload();
                }
              });
            }
        }
    });
    return false;
});

</script>
{% endblock %}